services:
  db:
    image: postgres:16-alpine
    restart: no
    environment:
      POSTGRES_USER: inv_user
      POSTGRES_PASSWORD: inv_pass
      POSTGRES_DB: drone_inventory_test
    ports:
      - "5434:5432"

volumes: {}
